### ISSUE TITLE
[General] Use a constant for the newline character instead of hardcoding `\n`

### ISSUE THREAD

**Issue by mhatzl** [unimarkup/unimarkup-rs#45]
Hardcoding `\n` inside strings may create problems on different operating systems.

Use a global constant that is set to the newline character (sequence) of the target operating system.

**Comment by nfejzic** [comment]
I think we handle this in a different way now (during lexing). Is the issue still relevant?

**Comment by mhatzl** [comment]
It would still be relevant for our output, but as discussed in this reddit post https://www.reddit.com/r/rust/comments/wxb7uu/how_to_handle_line_endings_when_writing_files/
we should just stick with `\n`, because most applications should be fine with it.
