### ISSUE TITLE
[REQ] Rework Inline formats using enum dispatch, like in main parser crate

### ISSUE THREAD

**Issue by nfejzic** [unimarkup/unimarkup-rs#94]
# The problem

Currently `Inline` is an enum, each variant having some kind of content type directly: 

```rust
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Inline {
    Bold(NestedContent),
    Italic(NestedContent),
    Underline(NestedContent),
    Verbatim(PlainContent),
    // ...
}
```

This implementation is hard to work with, and is not entirely type safe. For example, we switched to rendering via visitor (see #90), and as a consequence of this implementation, various `render_{inline_format}` functions get `NestedContent` or `PlainContent` as parameter, which is error prone (what stops us from passing `NestedContent` of `Italic` instead of `Bold`?).

Other than that, it might be nice to have different fields for different formats, like (specific) attributes, file paths in case of media inserts etc. 

# The solution

Therefore, since we already use enum for `Inline`, better solution would be to use similar pattern as the one in main parser:

```rust
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Inline {
    Bold(Bold),
    Italic(Italic),
    Underline(Underline),
    Verbatim(Verbatim),
    // ...
}
```

We can then dictate **exactly** what kind of content each format has, along with any additional fields and options we find necessary (or nice to have).

**Comment by mhatzl** [comment]
closed by PR #97
